# 访问端口
server:
  port: 8082

# druid 数据库连接池配置

spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1/taotao
      username: root
      password:
      druid:
        stat-view-servlet:
          allow: true
      redis:
          datasource: 1
          host: 127.0.0.1
          port: 6379
          password:
          pool:
            max-active: 8
            max-wait: -1
            max-idle: 8
            min-idle: 0
            timeout: 0
mapper:
  mappers: tk.mybatis.springboot.util.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging.level.org.springframework : WARN
logging.level.com.zly.mapper: DEBUG
logging.file: classpath:log/spring-boot-logging.log

spring.http.encoding.force: true
spring.http.encoding.charset: UTF-8
spring.http.encoding.enabled: true
server.tomcat.uri-encoding: UTF-8